name: ci-test-on-pullrequest
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: 
  pull_request:
    branches: [ "main" ]
    
jobs:
  ci-test-on-pullrequest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ trigger when pull request to main branch"
      
